### ISSUE TITLE
Errors if twtxt.txt is created with twtxt

### ISSUE THREAD

**Issue by durcheinandr** [JervisTetch/twtxt.vim#1]
Errors with tweets created with [twtxt](https://github.com/buckket/twtxt):

```
Line 20:
E402: Garbage after pattern: /^.\{-}Z/contains=twtxtTimestampC,twtxtTimestampD
E475: Invalid argument: twtxtTimestamp^I/^.\{-}Z/contains=twtxtTimestampC,twtxtTimestampD
Line 23:
E402: Garbage after pattern: /\(T\|Z\)/contained
E475: Invalid argument: twtxtTimeStampC^I/\(T\|Z\)/contained
Line 26:
E402: Garbage after pattern: /[\.:-]/contained
E475: Invalid argument: twtxtTimeStampD^I/[\.:-]/contained
``` 

Example tweet from original twtxt:

```
2017-03-03T18:04:37+01:00 #ignore testtweet for syntax checking with twtxt
```

**Comment by JervisTetch** [comment]
Oh my bad. I inserted some broken line continuation before uploading. Should be fixed now. Can you check again with twtxt?

**Comment by durcheinandr** [comment]
Fixed - no more errors but highlighting of date/time is broken (screenshot line 26 is tweet from twtxt):

![twtxt_syntax](https://cloud.githubusercontent.com/assets/9393265/23561971/da1a5df2-0040-11e7-8a11-fabe1da11c09.png)

**Comment by JervisTetch** [comment]
Fixed that.
